// Question :------

// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

 

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.



// Example 2:
// Input: s = "", t = "y"
// Output: "y"
 


// Constraints:
// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.



// Solution  :------

var findTheDifference = function(s, t) {
    var queue=[];
    var queue1=[];
    for(var i=0;i<t.length;i++){
        queue.push(t[i]);
    }
    for(var i=0;i<s.length;i++){
        queue1.push(s[i]);
    }
    console.log(queue);
    while(queue1.length!=0){
        if(queue[0]==queue1[0]){
            queue.shift();
            queue1.shift();
        }
        else{
            var k=queue.shift();
            queue.push(k)
        }
    }
    return queue[0]
};